# Generated by Django 6.0.2 on 2026-02-22 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "editor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        limit_choices_to={"role": "journalist"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for publisher content; leave blank for independent articles.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="news.publisher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "articles",
                    models.ManyToManyField(
                        blank=True, related_name="newsletters", to="news.article"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            ("role", "journalist"), ("role", "editor"), _connector="OR"
                        ),
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="newsletters_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalistSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "journalist",
                    models.ForeignKey(
                        limit_choices_to={"role": "journalist"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journalist_subscribers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        limit_choices_to={"role": "reader"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journalist_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("journalist", "reader")},
            },
        ),
        migrations.CreateModel(
            name="PublisherMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member_role",
                    models.CharField(
                        choices=[("editor", "Editor"), ("journalist", "Journalist")],
                        max_length=20,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="news.publisher",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publisher_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("publisher", "user", "member_role")},
            },
        ),
        migrations.CreateModel(
            name="PublisherSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="news.publisher",
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        limit_choices_to={"role": "reader"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publisher_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("publisher", "reader")},
            },
        ),
    ]
