# Generated by Django 6.0.2 on 2026-02-25 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("role__iexact", "Editor")),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("role__iexact", "Journalist")),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles_authored",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="journalistsubscription",
            name="journalist",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("role__iexact", "Journalist")),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journalist_subscribers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="journalistsubscription",
            name="reader",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("role__iexact", "Reader")),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journalist_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="author",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    ("role__iexact", "Journalist"),
                    ("role__iexact", "Editor"),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="newsletters_authored",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publishermembership",
            name="member_role",
            field=models.CharField(
                choices=[("Editor", "Editor"), ("Journalist", "Journalist")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="publishersubscription",
            name="reader",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("role__iexact", "Reader")),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publisher_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
