# Generated by Django 6.0.2 on 2026-02-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Reader", "Reader"),
                    ("Editor", "Editor"),
                    ("Journalist", "Journalist"),
                ],
                max_length=20,
            ),
        ),
    ]
